name = "repo-mod-viewer-api"
main = "worker.js"
compatibility_date = "2026-01-01"

[env.dev]
# Development environment configuration

[env.production]
# Production environment configuration
[env.production.vars]
# ALLOWED_ORIGIN = "https://atniptw.github.io"
